#!/bin/sh

#landscape (inverted)

xrandr -o left
xinput set-prop "Virtual core XTEST pointer" --type=float "Coordinate Transformation Matrix" 0 -1 1 1 0 0 0 0 1
xinput set-prop "SIS0457:00 0457:11ED" --type=float "Coordinate Transformation Matrix" 0 -1 1 1 0 0 0 0 1
